server:
  port: 8080
  servlet:
    context-path: /pengmai
spring:
  resources:
    static-locations: classpath:/static/
  profiles:
    active: dev
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: pengmai_db
      password: root
    url: jdbc:mysql://localhost:3306/pengmai_db?serverTimezone=GMT%2b8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 10240MB
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/